product_index:
    path:     /index
    defaults: { _controller: "EcommerceBundle:Product:index" }
    methods: GET

product_show:
    path:     /show/{id}
    defaults: { _controller: "EcommerceBundle:Product:show" }
    methods: GET

create_product_test:
    path:    /create
    defaults: { _controller: "EcommerceBundle:Product:createproduct" }
    methods: POST
