panier_add:
    path:     /add
    defaults: { _controller: "EcommerceBundle:Panier:add" }
    options:
        expose: true

panier_show:
    path:    /show
    defaults: { _controller: "EcommerceBundle:Panier:show" }

panier_delete:
    path:     /delete
    defaults: { _controller: "EcommerceBundle:Panier:delete" }
    options:
        expose: true

panier_update:
    path:     /update
    defaults: { _controller: "EcommerceBundle:Panier:update" }
    options:
        expose: true

panier_valider:
    path:     /valider
    defaults: { _controller: "EcommerceBundle:Panier:valider" }

