comment_new:
    path:     /new/{id}
    defaults: { _controller: "EcommerceBundle:Comment:new" }
    methods: GET|POST

comment_show:
    path: /show
    defaults: { _controller: "EcommerceBundle:Comment:show" }
    methods: GET

