panier_add:
    path:     /add
    defaults: { _controller: "EcommerceBundle:Panier:add" }

panier_show:
    path:    /show
    defaults: { _controller: "EcommerceBundle:Panier:show" }

panier_delete:
    path:     /delete
    defaults: { _controller: "EcommerceBundle:Panier:delete" }

