parameters:
    class.compteur: EcommerceBundle\Listener\Compteur_commentListener


services:
#    ecommerce.example:
#        class: EcommerceBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    ecommerce.compteur.commentaire.service:
        class: '%class.compteur%'
        tags:
            - { name: doctrine.event_listener , event: postPersist }

