parameters:
    class.compteur: EcommerceBundle\Listener\Compteur_commentListener
    class.calcul.cout.product: EcommerceBundle\Service\CalculSomme
    class.calcul_cout.product_twig.extension: EcommerceBundle\Service\CalculSommeExtensionTwig


services:
#    ecommerce.example:
#        class: EcommerceBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    ecommerce.compteur.commentaire.service:
        class: '%class.compteur%'
        tags:
            - { name: doctrine.event_listener , event: postPersist }


    ecommerce.cout.product.service:
        class: '%class.calcul.cout.product%'
        arguments: ["@session", "@doctrine.orm.entity_manager"]


    ecommerce.cout.product_twig_extension.service:
        class: '%class.calcul_cout.product_twig.extension%'
        arguments: ['@ecommerce.cout.product.service']
        tags:
            - { name: twig.extension }

